language: node_js
sudo: false
node_js:
  - 6
  - 7

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn lint && yarn cover

after_success:
  - cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js
